### ISSUE TITLE
Aufgabenstellung

### ISSUE THREAD

**Issue by BieberleA** [j-stephan/gb#1]
Bitte mal noch die offizielle Aufgabenstellung hinzufügen. Danke.

**Comment by BieberleA** [comment]
Kann ich wirklich niemanden assignen???

**Comment by j-stephan** [comment]
Nein, da das mein privater Account ist. Aber keine Angst, ich sehe hier alles automatisch, da ich per eMail benachrichtigt werde.

**Comment by j-stephan** [comment]
Genügt der Text der Aufgabenstellung oder lieber das PDF? Bin mir nicht sicher, ob Prof. Nagel es so gut findet, wenn seine Unterschrift im Internet herumgeistert.

**Comment by BieberleA** [comment]
ja --- der Text reicht zu
